version: '3'

services:
  web:
    build: .
    command: 
      - bash
      - -c
      - |
        python manage.py migrate && 
        python user_generation_script.py &&
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:12.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "Test@123"
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  static_volume: {}
  db:
    driver: local