# Generated by Django 5.0.3 on 2024-04-05 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend1', models.ForeignKey(help_text='One of the users who are friends.', on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to=settings.AUTH_USER_MODEL)),
                ('friend2', models.ForeignKey(help_text='The other user who is friends with the first user.', on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friends',
                'verbose_name_plural': 'Friends',
                'unique_together': {('friend1', 'friend2')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the friend request was sent.')),
                ('accepted', models.BooleanField(default=False, help_text='Indicates whether the friend request has been accepted.')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='The date and time when the friend request was accepted, if accepted.', null=True)),
                ('rejected', models.BooleanField(default=False, help_text='Indicates whether the friend request has been rejected.')),
                ('rejected_at', models.DateTimeField(blank=True, help_text='The date and time when the friend request was rejected, if rejected.', null=True)),
                ('from_user', models.ForeignKey(help_text='The user who sent the friend request.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(help_text='The user who received the friend request.', on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friend Request',
                'verbose_name_plural': 'Friend Requests',
                'ordering': ['-created_at'],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
